function Hd = butterworthBandpassFilter(Fs, N, Fc1, Fc2)
%BUTTERWORTHBANDPASSFILTER Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 7.12 and the DSP System Toolbox 8.0.
%
% Generated on: 26-Aug-2012 23:15:43
%

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% % All frequency values are in Hz.
% Fs = 30;  % Sampling Frequency
% 
% N   = 256;   % Order
% Fc1 = 0.83;  % First Cutoff Frequency
% Fc2 = 1;     % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
Hd = design(h, 'butter');

% [EOF]

end
